package com.mycompany.trabalhofinal.visao;

import com.mycompany.trabalhofinal.modelo.Cliente;
import com.mycompany.trabalhofinal.modelo.Filme;
import com.mycompany.trabalhofinal.modelo.Item;
import com.mycompany.trabalhofinal.modelo.Locadora;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;


//@author carlo
public class JanelaTrabalho extends javax.swing.JFrame {

    private Locadora locadora;
    
    public JanelaTrabalho() {
        initComponents();
        locadora = new Locadora();
        atualizarComboBoxFilmes();
        atualizarComboBoxClientes();
        atualizarComboBoxFilmesAlugados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog5 = new javax.swing.JDialog();
        jDialog6 = new javax.swing.JDialog();
        jDialog7 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jDialog8 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jFrame2 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cineflix = new javax.swing.JLabel();
        cineflix1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome_cadastro_filme = new javax.swing.JTextField();
        genero_cadastro_filme = new javax.swing.JTextField();
        ano_cadastro_filme = new javax.swing.JTextField();
        unidades_cadastro_filme = new javax.swing.JTextField();
        sinopse_cadastro_filme = new javax.swing.JTextField();
        cadastrar_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filmes = new javax.swing.JComboBox<>();
        alugar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        genero_filme = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ano_filme = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        unidades_filme = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sinopse_filme = new javax.swing.JTextField();
        remove_cat = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cadastrar_cliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        clientes = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        filme_alugado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        data_devolucao = new javax.swing.JTextField();
        remover_cliente = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        nome_cliente = new javax.swing.JTextField();
        devolver = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        filmes1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        clientes_datas = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialog5.getContentPane());
        jDialog5.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialog6.getContentPane());
        jDialog6.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog6Layout.setVerticalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog7Layout = new javax.swing.GroupLayout(jDialog7.getContentPane());
        jDialog7.getContentPane().setLayout(jDialog7Layout);
        jDialog7Layout.setHorizontalGroup(
            jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog7Layout.setVerticalGroup(
            jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog8Layout = new javax.swing.GroupLayout(jDialog8.getContentPane());
        jDialog8.getContentPane().setLayout(jDialog8Layout);
        jDialog8Layout.setHorizontalGroup(
            jDialog8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog8Layout.setVerticalGroup(
            jDialog8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Na CineFlix, cada filme é uma nova viagem!\nDos grandes sucessos de Hollywood aos cults mais  aclamados, \ntemos o título perfeito para sua próxima sessão. \nAlugue com facilidade, descubra novos favoritos e \naproveite o melhor do cinema quando e onde quiser. \nPorque boas histórias nunca saem de cartaz! 🎥🍿");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleDescription("");

        cineflix.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        cineflix.setText("Sua próxima sessão começa aqui!");

        cineflix1.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        cineflix1.setText("CineFlix");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cineflix)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(cineflix1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(cineflix1)
                .addGap(18, 18, 18)
                .addComponent(cineflix)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Principal", jPanel1);

        jLabel2.setText("Nome:");

        jLabel3.setText("Gênero:");

        jLabel4.setText("Lançamento:");

        jLabel5.setText("Unidades:");

        jLabel6.setText("Sinopse:");

        nome_cadastro_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_cadastro_filmeActionPerformed(evt);
            }
        });

        genero_cadastro_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genero_cadastro_filmeActionPerformed(evt);
            }
        });

        ano_cadastro_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ano_cadastro_filmeActionPerformed(evt);
            }
        });

        unidades_cadastro_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidades_cadastro_filmeActionPerformed(evt);
            }
        });

        sinopse_cadastro_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinopse_cadastro_filmeActionPerformed(evt);
            }
        });

        cadastrar_button.setText("Cadastrar");
        cadastrar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome_cadastro_filme, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(genero_cadastro_filme)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ano_cadastro_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(unidades_cadastro_filme)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(sinopse_cadastro_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(cadastrar_button)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nome_cadastro_filme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genero_cadastro_filme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ano_cadastro_filme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(unidades_cadastro_filme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sinopse_cadastro_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(cadastrar_button)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Filme", jPanel2);

        jLabel7.setText("Filme:");

        filmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmesActionPerformed(evt);
            }
        });

        alugar.setText("Alugar");
        alugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alugarActionPerformed(evt);
            }
        });

        jLabel9.setText("Gênero:");

        genero_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genero_filmeActionPerformed(evt);
            }
        });

        jLabel10.setText("Lançamento:");

        ano_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ano_filmeActionPerformed(evt);
            }
        });

        jLabel11.setText("Unidades:");

        unidades_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidades_filmeActionPerformed(evt);
            }
        });

        jLabel12.setText("Sinopse:");

        sinopse_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinopse_filmeActionPerformed(evt);
            }
        });

        remove_cat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remove_cat.setForeground(new java.awt.Color(255, 0, 0));
        remove_cat.setText("Remover do Catálogo");
        remove_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_catActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(23, 23, 23)
                        .addComponent(unidades_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sinopse_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alugar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(filmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ano_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(genero_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(remove_cat)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(filmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genero_filme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ano_filme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(unidades_filme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(sinopse_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(alugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remove_cat)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Catálogo", jPanel3);

        cadastrar_cliente.setText("Cadastrar Novo Cliente");
        cadastrar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_clienteActionPerformed(evt);
            }
        });

        jLabel8.setText("ID:");

        clientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        jLabel13.setText("Filme Alugado:");

        jLabel14.setText("Data de devolução:");

        remover_cliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remover_cliente.setForeground(new java.awt.Color(255, 0, 0));
        remover_cliente.setText("Remover Cliente");
        remover_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_clienteActionPerformed(evt);
            }
        });

        jLabel18.setText("Cliente:");

        devolver.setText("Devolver");
        devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(filme_alugado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(data_devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(devolver)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remover_cliente)
                            .addComponent(cadastrar_cliente))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cadastrar_cliente)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(filme_alugado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(data_devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(devolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(remover_cliente)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Clientes", jPanel4);

        jLabel15.setText("Filme:");

        filmes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filmes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmes1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Clientes/Datas devolução:");

        clientes_datas.setColumns(20);
        clientes_datas.setRows(5);
        clientes_datas.setText("Cliente 1 / 01/01/01");
        jScrollPane4.setViewportView(clientes_datas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filmes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(filmes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alugueis", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sinopse_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinopse_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinopse_filmeActionPerformed

    private void unidades_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidades_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidades_filmeActionPerformed

    private void ano_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ano_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ano_filmeActionPerformed

    private void genero_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genero_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genero_filmeActionPerformed

    private void alugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alugarActionPerformed
    String nomeFilmeSelecionado = (String) filmes.getSelectedItem();
    String nomeClienteSelecionado = (String) clientes.getSelectedItem();
    String dataDevolucao = JOptionPane.showInputDialog(this, "Digite a data de devolução:");

    if (nomeFilmeSelecionado != null && nomeClienteSelecionado != null && dataDevolucao != null) {
        Filme filmeSelecionado = locadora.getManipulaFilmes().getFilmePorNome(nomeFilmeSelecionado);
        Cliente clienteSelecionado = locadora.getManipulaClientes().getClientePorNome(nomeClienteSelecionado);

        if (filmeSelecionado != null && clienteSelecionado != null && filmeSelecionado.getUnidades() > 0) {
            locadora.alugarFilme(clienteSelecionado, filmeSelecionado, dataDevolucao);
            JOptionPane.showMessageDialog(this, "Filme alugado com sucesso!");
            atualizarComboBoxFilmesAlugados(); // Atualiza a JComboBox de filmes
        } else {
            JOptionPane.showMessageDialog(this, "Não há unidades disponíveis ou cliente não encontrado.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um filme e um cliente.");
    }
    locadora.getManipulaClientes().salvarClientes();
    locadora.getManipulaFilmes().salvarFilmes();
    }//GEN-LAST:event_alugarActionPerformed

    private void remove_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_catActionPerformed
         String nomeFilmeSelecionado = (String) filmes.getSelectedItem();
    Filme filmeSelecionado = locadora.getManipulaFilmes().getFilmePorNome(nomeFilmeSelecionado);

    if (filmeSelecionado != null) {
        // Remove o filme da locadora
        locadora.getManipulaFilmes().removerFilme(filmeSelecionado);
        
        // Atualiza a JComboBox para refletir a remoção
        atualizarComboBoxFilmes();
        atualizarComboBoxFilmesAlugados();
        
        // Limpa os campos de texto
        genero_filme.setText("");
        ano_filme.setText("");
        unidades_filme.setText("");
        sinopse_filme.setText("");
        
        // Exibe uma mensagem de confirmação
        JOptionPane.showMessageDialog(this, "Filme removido do catálogo com sucesso!");
    } else {
        // Exibe uma mensagem de erro se nenhum filme estiver selecionado
        JOptionPane.showMessageDialog(this, "Nenhum filme selecionado para remover.");
    }
    }//GEN-LAST:event_remove_catActionPerformed

    private void cadastrar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_clienteActionPerformed
    JanelaCliente dialog = new JanelaCliente(this);
    dialog.setVisible(true);
    
    if (dialog.isConfirmado()) {
        Cliente novoCliente = new Cliente(dialog.getNomeCliente(), dialog.getIdCliente());
        locadora.adicionaCliente(novoCliente);
        atualizarComboBoxClientes(); // Atualiza a JComboBox após adicionar um cliente
    }
    }//GEN-LAST:event_cadastrar_clienteActionPerformed

    private void remover_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_clienteActionPerformed
    String nomeClienteSelecionado = (String) clientes.getSelectedItem();
    Cliente clienteSelecionado = locadora.getManipulaClientes().getClientes().stream()
            .filter(cliente -> cliente.getNome().equals(nomeClienteSelecionado))
            .findFirst()
            .orElse(null);

    if (clienteSelecionado != null) {
        locadora.removerCliente(clienteSelecionado);
        atualizarComboBoxClientes(); // Atualiza a JComboBox após remover um cliente
        // Limpa os campos de texto
        nome_cliente.setText("");
        // Limpe outros campos se necessário
        JOptionPane.showMessageDialog(this, "Cliente removido com sucesso!");
    } else {
        JOptionPane.showMessageDialog(this, "Nenhum cliente selecionado para remover.");
    }
       
    }//GEN-LAST:event_remover_clienteActionPerformed

    private void sinopse_cadastro_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinopse_cadastro_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinopse_cadastro_filmeActionPerformed

    private void unidades_cadastro_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidades_cadastro_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidades_cadastro_filmeActionPerformed

    private void ano_cadastro_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ano_cadastro_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ano_cadastro_filmeActionPerformed

    private void genero_cadastro_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genero_cadastro_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genero_cadastro_filmeActionPerformed

    private void nome_cadastro_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_cadastro_filmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_cadastro_filmeActionPerformed

    private void cadastrar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_buttonActionPerformed
    String titulo = nome_cadastro_filme.getText();
    String genero = genero_cadastro_filme.getText();
    int quantidade = Integer.parseInt(unidades_cadastro_filme.getText());
    int data = Integer.parseInt(ano_cadastro_filme.getText());
    String sinopse = sinopse_cadastro_filme.getText();
    
    locadora.adicionaFilme(new Filme(titulo, genero, data, quantidade, sinopse));
    atualizarComboBoxFilmes();
        
    nome_cadastro_filme.setText("");
    genero_cadastro_filme.setText("");
    unidades_cadastro_filme.setText("");
    ano_cadastro_filme.setText("");
    sinopse_cadastro_filme.setText("");
    }//GEN-LAST:event_cadastrar_buttonActionPerformed

    private void atualizarComboBoxFilmes() {
    filmes.removeAllItems(); // Limpa os itens existentes
    for (Filme filme : locadora.getManipulaFilmes().getFilmes()) { // Supondo que você tenha um método para obter os filmes
        filmes.addItem(filme.getNome()); // Adiciona o nome do filme à JComboBox
    }
}
    
    private void filmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmesActionPerformed
            String nomeFilmeSelecionado = (String) filmes.getSelectedItem();
    Filme filmeSelecionado = locadora.getManipulaFilmes().getFilmePorNome(nomeFilmeSelecionado);

    if (filmeSelecionado != null) {
        // Atualiza os campos com os dados do filme
        genero_filme.setText(filmeSelecionado.getGenero());
        ano_filme.setText(String.valueOf(filmeSelecionado.getAnoLancamento()));
        unidades_filme.setText(String.valueOf(filmeSelecionado.getUnidades()));
        sinopse_filme.setText(filmeSelecionado.getSinopse());
    }
    }//GEN-LAST:event_filmesActionPerformed

    private void atualizarComboBoxClientes() {
    clientes.removeAllItems(); // Limpa os itens existentes
    for (Cliente cliente : locadora.getManipulaClientes().getClientes()) { // Supondo que você tenha um método para obter os clientes
        clientes.addItem(cliente.getNome()); // Adiciona o nome do cliente à JComboBox
    }
}
    
    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
    String nomeClienteSelecionado = (String) clientes.getSelectedItem();
    Cliente clienteSelecionado = locadora.getManipulaClientes().getClientePorNome(nomeClienteSelecionado); // Usando o novo método

    if (clienteSelecionado != null) {
        // Atualiza os campos com os dados do cliente
        nome_cliente.setText(clienteSelecionado.getId());
        if(clienteSelecionado.getFilmeAlugado()!=null){
        filme_alugado.setText(clienteSelecionado.getFilmeAlugado().getNome());
        data_devolucao.setText(clienteSelecionado.getDataDevolucao());}
        // Se houver outros campos, atualize-os aqui, por exemplo:
        // id_cliente.setText(clienteSelecionado.getId());
    else{
        filme_alugado.setText("");
        data_devolucao.setText("");}
    }
    }//GEN-LAST:event_clientesActionPerformed

    private void atualizarComboBoxFilmesAlugados() {
    filmes1.removeAllItems(); // Limpa os itens existentes
    for (Filme filme : locadora.getManipulaFilmes().getFilmes()) { // Supondo que você tenha um método para obter os filmes
        filmes1.addItem(filme.getNome()); // Adiciona o nome do filme à JComboBox
    }
}
    
    private void filmes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmes1ActionPerformed
        String nomeFilmeSelecionado = (String) filmes1.getSelectedItem();
    Filme filmeSelecionado = locadora.getManipulaFilmes().getFilmePorNome(nomeFilmeSelecionado);

    if (filmeSelecionado != null) {
        // Limpa a área de texto antes de exibir os novos dados
        clientes_datas.setText("");

        // Exibe os detalhes dos clientes que alugaram o filme
        StringBuilder detalhesClientes = new StringBuilder();
        for (Cliente cliente : locadora.getManipulaClientes().getClientes()) {
            if (cliente.getFilmeAlugado() != null && cliente.getFilmeAlugado().getNome().equals(nomeFilmeSelecionado)) {
                detalhesClientes.append("Nome: ").append(cliente.getNome())
                                .append(", ID: ").append(cliente.getId())
                                .append(", Data de Devolução: ").append(cliente.getDataDevolucao())
                                .append("\n");
            }
        }

        // Atualiza a área de texto com os detalhes dos clientes
        if (detalhesClientes.length() > 0) {
            clientes_datas.setText(detalhesClientes.toString());
        } else {
            clientes_datas.setText("Nenhum cliente alugou este filme.");
        }
    }
    }//GEN-LAST:event_filmes1ActionPerformed

    private void devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverActionPerformed
        String nomeClienteSelecionado = (String) clientes.getSelectedItem();

    if (nomeClienteSelecionado != null) {
        Cliente clienteSelecionado = locadora.getManipulaClientes().getClientePorNome(nomeClienteSelecionado);

        if (clienteSelecionado != null) {
            locadora.devolverFilme(clienteSelecionado);
            JOptionPane.showMessageDialog(this, "Filme devolvido com sucesso!");
            atualizarComboBoxFilmesAlugados(); // Atualiza a JComboBox de filmes
        } else {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado ou cliente não alugou nenhum filme.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um cliente.");
    }
    filme_alugado.setText("");
    data_devolucao.setText("");
    }//GEN-LAST:event_devolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaTrabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alugar;
    private javax.swing.JTextField ano_cadastro_filme;
    private javax.swing.JTextField ano_filme;
    private javax.swing.JButton cadastrar_button;
    private javax.swing.JButton cadastrar_cliente;
    private javax.swing.JLabel cineflix;
    private javax.swing.JLabel cineflix1;
    private javax.swing.JComboBox<String> clientes;
    private javax.swing.JTextArea clientes_datas;
    private javax.swing.JTextField data_devolucao;
    private javax.swing.JButton devolver;
    private javax.swing.JTextField filme_alugado;
    private javax.swing.JComboBox<String> filmes;
    private javax.swing.JComboBox<String> filmes1;
    private javax.swing.JTextField genero_cadastro_filme;
    private javax.swing.JTextField genero_filme;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JDialog jDialog8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nome_cadastro_filme;
    private javax.swing.JTextField nome_cliente;
    private javax.swing.JButton remove_cat;
    private javax.swing.JButton remover_cliente;
    private javax.swing.JTextField sinopse_cadastro_filme;
    private javax.swing.JTextField sinopse_filme;
    private javax.swing.JTextField unidades_cadastro_filme;
    private javax.swing.JTextField unidades_filme;
    // End of variables declaration//GEN-END:variables
}
